version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Puerto para las conexiones de RabbitMQ
      - "15672:15672"     # Puerto para la consola de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest      # Usuario por defecto
      RABBITMQ_DEFAULT_PASS: guest  # Contraseña por defecto
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistencia de datos

volumes:
  rabbitmq_data:
