# Usar la imagen de OpenJDK como base
FROM openjdk:21-jdk-slim
# Copiar el archivo JAR generado por Maven o Gradle al contenedor
COPY target/api_gateway_ms-0.0.1-SNAPSHOT.jar api_gateway_ms_app.jar
# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "api_gateway_ms_app.jar"]