version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: "http://keycloak:8080"
      KEYCLOAK_HOSTNAME: "keycloak"
      KEYCLOAK_HOSTNAME_PORT: 8080
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - shared_network

volumes:
  keycloak_data:

networks:
  shared_network:
    external: true