version: '3'

services:
  notification-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=host.docker.internal