# Usar la imagen de OpenJDK como base
FROM openjdk:21-jdk-slim
# Copiar el archivo JAR generado por Maven o Gradle al contenedor
COPY target/user_management_ms-0.0.1-SNAPSHOT.jar user_management_ms_app.jar
# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "user_management_ms_app.jar"]