version: '3.8'

services:
  user-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Puerto de la aplicación
    depends_on:
      postgresbd:
        condition: service_healthy
    environment:
      - DATASOURCE_URL=${SPRING_POSTGRES_URL}
      - DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - DATASOURCE_DRIVER_CLASS_NAME=${POSTGRES_DRIVER}
      - HIBERNATE_DDL_AUTO=${SPRING_DLL_JPA}
      - LOG_QUERIES_SLOWER_THAN_MS=${NUM_LOG}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_JWK_SET_URI=${KEYCLOAK_JWK_SET_URI}

  postgresbd:
    image: postgres:alpine
    container_name: postgresbd
    restart: always
    volumes:
      - ~/docker-volumes/personal/Activate/user-server-postgres:/var/lib/postgresql
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 1s
      retries: 5